### ISSUE TITLE
An issue that's not really an issue...

### ISSUE THREAD

**Issue by aoedipus** [tomik23/Leaflet.Autocomplete#1]
Hello, and thank you for creating such a lovely tool! I am wondering if you might be willing to share an unminified version of autosuggest.js just to help with debugging? I have been experiencing some oddness with returns that I would like to get to the bottom of. All the best.

**Comment by tomik23** [comment]
Hi, today I made a big change to the **Leaflet.Autocomplete** example because the **autosuggest** library has changed. Now the example is clearer, at least I hope so ;)
As for the **autosuggest** library, the link to it is given in the content, maybe the link is not readable enough.
So I'll give it here [autosuggest](https://github.com/tomik23/autosuggest/)

**Comment by aoedipus** [comment]
Hi! Thank you for the reply. I will look at the updated leaflet version. I
did indeed see the link to autocomplete, and followed it. But when I
referenced that script instead of the unminified version earlier today,
things broke rather badly so I gave up. Perhaps it was due to the changes
you mentioned, and I was a bit too soon.
